# Tema 1

* Înainte de trimiterea temei, verificați obligatoriu că toate cerințele sunt îndeplinite. 
* Notebook-ul trebuie să ruleze în întregime fără erori folosind comanda Kernel → Run All. Orice excepție care întrerupe execuția va determina punctarea temei doar până la punctul respectiv.
* Vă rog să reazlizați toate importările de pachete în celula de cod de mai jos.
* Se acorđa __1 punct__ din oficiu.

In [41]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler,StandardScaler
from sklearn.impute import SimpleImputer

## Enunțuri

1. (2 puncte) Se consideră o matrice de tip NumPy. Să se returneze matricea standardizată astfel:

Pentru fiecare coloană:

* Se calculează media și deviația standard a coloanei

* Se scade media din fiecare element al coloanei 

* Se împarte rezultatul la deviația standard a coloanei (Atenție la împărțirea la 0)

* Caz special: Dacă o coloană este constantă (deviația standard = 0), se păstrează valorile originale (folosiți np.allclose() pentru toleranță la erori de floating point)

Validați rezultatul prin comparație cu [__StandardScaler__ (link)](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html) din scikit-learn, afișați diferențele dintre implementări (puteți folosi funcția np.abs)



In [42]:
def MatriceaStandardizata(A):
    A_aux1 = A.copy().astype(float)
    for j in range(A_aux1.shape[1]):
        media=np.mean(A_aux1[:,j])
        deviatia=np.std(A_aux1[:,j])
        if(np.allclose(deviatia,0)):
            continue
        else:
            A_aux1[:,j]=(A_aux1[:,j]-media)/deviatia
    return A_aux1

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
print(MatriceaStandardizata(A))
print(' ')

scaler=StandardScaler()
rezultat_scaler=scaler.fit_transform(A)
print(rezultat_scaler)
print(' ')

[[-1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487]]
 
[[-1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487]]
 


2. (2 puncte) Implementați o funcție care primește o matrice de tip NumPy și aplică **normalizarea min-max** pe fiecare coloană, transformând valorile în intervalul [0, 1] folosind formula: $$\frac{valoare - min\_coloană} {max\_coloană - min\_coloană} $$

Se presupune că nicio coloană nu este constantă.

Validați rezultatul prin comparație cu [__MinMaxScaler__ (link)](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.MinMaxScaler.html) din scikit-learn, afișați diferențele dintre implementări (puteți folosi funcția np.abs)



In [43]:
def NormalizareMinMax(A):
    A_aux=A.copy().astype(float)
    for j in range(A_aux.shape[1]):
        minCol=np.min(A_aux[:,j])
        maxCol=np.max(A_aux[:,j])
        A_aux[:,j]=(A_aux[:,j]-minCol)/(maxCol-minCol)
    return A_aux

A=np.array([[1, 2, 3],
           [4, 5, 6],
           [7, 8, 9]])

rezultat=NormalizareMinMax(A)
print(rezultat)
print(' ')

scaler=MinMaxScaler()
rezultat_scikit=scaler.fit_transform(A)
print(rezultat_scikit)
print(' ')

diferenta=np.abs(rezultat - rezultat_scikit)
print(diferenta)
print(' ')
        

[[0.  0.  0. ]
 [0.5 0.5 0.5]
 [1.  1.  1. ]]
 
[[0.  0.  0. ]
 [0.5 0.5 0.5]
 [1.  1.  1. ]]
 
[[0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 5.55111512e-17 0.00000000e+00]
 [1.11022302e-16 0.00000000e+00 0.00000000e+00]]
 


3. (2 puncte) Implementați o funcție care primește o matrice de tip NumPy și înlocuiește valorile NaN cu media coloanei respective.

Comparați rezultatul cu [__SimpleImputer__ (link)](https://scikit-learn.org/stable/modules/generated/sklearn.impute.SimpleImputer.html) din scikit-learn folosind strategia "mean", afișați diferențele dintre implementări (puteți folosi funcția np.abs).

In [44]:
def InlocuireNaN(A):
    A_aux2=A.copy().astype(float)
    for i in range(A_aux2.shape[0]):
        for j in range(A_aux2.shape[1]):
            if(np.isnan(A_aux2[i][j])):
                A_aux2[i][j]=np.nanmean(A_aux2[:,j])
    return A_aux2

A=np.array([[1, 2, np.nan],
           [4, np.nan, 6],
           [7, 8, 9]])

print(InlocuireNaN(A))
print(' ')

imputer = SimpleImputer(strategy="mean")
rezultat_imputer = imputer.fit_transform(A)
print(rezultat_imputer)
print(' ')

diferenta = np.abs(InlocuireNaN(A)-rezultat_imputer)
print(diferenta)
print(' ')

[[1.  2.  7.5]
 [4.  5.  6. ]
 [7.  8.  9. ]]
 
[[1.  2.  7.5]
 [4.  5.  6. ]
 [7.  8.  9. ]]
 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
 


4. (2 puncte) Se citește un text dintr-un fișier txt. Se cer următoarele:
* Numărul total de caractere
* Eliminarea semnele de punctuație
* Convertirea tuturor cuvintelor în litere mici
* Numărul total de cuvinte
* Numărul total de rânduri
* Lungimea medie a cuvintelor
* Lista cuvintelor unice (apare o singură dată)
* Lista cuvintelor duplicate (apare de ≥ 2 ori)
* Numărul total de cuvinte unice
* Calculează statistici detaliate:
    - Numărul de vocale/consoane
    - Cuvântul cel mai lung
    - Raportul cuvinte unice / total cuvinte
    - Densitatea cuvintelor (cuvinte/caractere)

In [59]:
def citeste_fisier_simplu(nume_fisier):
    """
    Citește întregul conținut al fișierului ca un singur string
    """
    try:
        with open(nume_fisier, 'r', encoding='utf-8') as f:
            continut = f.read()
        return continut
    except FileNotFoundError:
        print(f"Eroare: Fișierul {nume_fisier} nu există!")
        return None
    except Exception as e:
        print(f"Eroare la citire: {e}")
        return None

# Utilizare
text = citeste_fisier_simplu('Pupăza_din_tei.txt')
if text:
    print("Text citit:")
    print(text)

Text citit:
Amintiri din copilărie - Pupăza din tei
de Ion Creangă

Mă trezeşte mama într-o dimineaţă din somn, cu
vai-nevoie, zicându-mi: Scoală, duglişule, înainte de răsăritul soarelui; iar vrei să te pupe cucul armenesc şi să te
spurce, ca să nu-ţi meargă bine toată ziua?... Căci aşa ne amăgea mama cu o pupăză care-şi făcea cuib, de mulţi ani,
într-un tei foarte bătrân şi scorburos, pe coasta dealului, la moş Andrei, fratele tatei cel mai mic. Şi numai ce-o
auzeai vara: Pu-pu-pup! Pu-pu-pup! dis-dimineaţă, în toate zilele, de vuia satul. Şi cum mă scol, îndată mă şi trimite
mama cu demâncare în ţarină, la nişte lingurari ce-i aveam tocmiţi prăşitori, tocmai în Valea-Seacă, aproape de
Topoliţa. Şi pornind eu cu demâncarea, numai ce şi aud pupăza cântând:
— Pu-pu-pup! pu-pu-pup! pu-pu-pup!
Eu, atunci, să nu-mi caut de drum tot înainte? mă abat pe la tei, cu gând să prind pupăza, căci aveam grozavă ciudă
pe dânsa: nu numaidecât pentru pupat, cum zicea mama, ci pentru că mă scula în to

In [61]:
#  Numărul total de caractere
print("Numarul total de caractere este: ",len(text))

# * Eliminarea semnele de punctuație
punctuatia = ['.',',','!','?',';',':','-','(',')','"',"'","_","—"]
text_faraPunctuatie = text
for semn in punctuatia:
    text_faraPunctuatie=text_faraPunctuatie.replace(semn,"")
print("Text fara semne de punctuatie: ",text_faraPunctuatie)
print(' ')

# * Convertirea tuturor cuvintelor în litere mici
text_mic=text_faraPunctuatie.lower()
print("Textul cu literele mici:\n\n", text_mic)

# * Numărul total de cuvinte
cuvinte=text_faraPunctuatie.split()
print(len(cuvinte))

# * Numărul total de rânduri
numarRanduri = len(text.splitlines())
print(numarRanduri)

# * Lungimea medie a cuvintelor
mediaLungimeCuvinte=(sum(len(cuvant) for cuvant in cuvinte)/len(cuvinte))
print(mediaLungimeCuvinte)
print(' ')

# * Lista cuvintelor unice (apare o singură dată)
cuvinteUnice=[cuvant for cuvant in cuvinte if cuvinte.count(cuvant)==1]
print(cuvinteUnice)
print(' ')

# * Lista cuvintelor duplicate (apare de ≥ 2 ori)
cuvinteDuplicate=[cuvant for cuvant in cuvinte if cuvinte.count(cuvant)>=2]
print(cuvinteDuplicate)
print(' ')

# * Numărul total de cuvinte unice
print(len(cuvinteUnice))

# * Calculează statistici detaliate:
#     - Numărul de vocale/consoane
vocale = "aeiouAEIOU"
numarVocale=0
numarConsoane=0
for cuvant in cuvinte:
    for litera in cuvant:
        if litera in vocale:
            numarVocale +=1
        elif litera.isalpha():
             numarConsoane+=1
print(numarVocale)
print(numarConsoane)

#     - Cuvântul cel mai lung
cuvantLung=" "
lungimeMax=0
for cuvant in cuvinte:
    if(len(cuvant)>lungimeMax):
        lungimeMax=len(cuvant)
        cuvantLung=cuvant
print("Cuvantul de lungime maxima este: ", cuvantLung)

#     - Raportul cuvinte unice / total cuvinte
print("Raport cuvinte unice/total cuvinte: ", len(cuvinteUnice)/len(cuvinte))

#     - Densitatea cuvintelor (cuvinte/caractere)
print("Densitatea cuvintelor: ", len(cuvinte)/len(text_mic))


Numarul total de caractere este:  8550
Text fara semne de punctuatie:  Amintiri din copilărie  Pupăza din tei
de Ion Creangă

Mă trezeşte mama întro dimineaţă din somn cu
vainevoie zicândumi Scoală duglişule înainte de răsăritul soarelui iar vrei să te pupe cucul armenesc şi să te
spurce ca să nuţi meargă bine toată ziua Căci aşa ne amăgea mama cu o pupăză careşi făcea cuib de mulţi ani
întrun tei foarte bătrân şi scorburos pe coasta dealului la moş Andrei fratele tatei cel mai mic Şi numai ceo
auzeai vara Pupupup Pupupup disdimineaţă în toate zilele de vuia satul Şi cum mă scol îndată mă şi trimite
mama cu demâncare în ţarină la nişte lingurari cei aveam tocmiţi prăşitori tocmai în ValeaSeacă aproape de
Topoliţa Şi pornind eu cu demâncarea numai ce şi aud pupăza cântând
 Pupupup pupupup pupupup
Eu atunci să numi caut de drum tot înainte mă abat pe la tei cu gând să prind pupăza căci aveam grozavă ciudă
pe dânsa nu numaidecât pentru pupat cum zicea mama ci pentru că mă scula în toate z

 5. (1 punct) Considerăm o matrice de adiacență pentru a descrie relațiile de prietenii între utilizatorii unei rețele de socializare.

 a) Calculați numărul de prieteni pentru fiecare user în parte.

 b) Determinați persoanele "populare" (au mai mult de 2 prieteni).

 c) Determinați persoanele care sunt prietene reciproc. 

    

In [62]:
# Friendship network (adjacency matrix)
# 1 indicates friendship, 0 indicates no friendship
friendships = np.array([
    [0, 1, 1, 0, 1],  # User 0's friends
    [1, 0, 1, 1, 0],  # User 1's friends
    [1, 1, 0, 0, 1],  # User 2's friends
    [0, 1, 0, 0, 1],  # User 3's friends
    [1, 0, 1, 1, 0]   # User 4's friends
])

# a) 
friend_counts = np.sum(friendships,axis=0)
print(friend_counts)

# b) 
popular_users = [i for i in range(friendships.shape[0])
                     if(friend_counts[i]>2)]
print(popular_users)

# c) 
mutual_friends = [(i,j) for i in range(friendships.shape[0])
                          for j in range(friendships.shape[1])
                              if(friendships[i][j] == 1 and friendships[j][i] == 1)]
print(mutual_friends)

[3 3 3 2 3]
[0, 1, 2, 4]
[(0, 1), (0, 2), (0, 4), (1, 0), (1, 2), (1, 3), (2, 0), (2, 1), (2, 4), (3, 1), (3, 4), (4, 0), (4, 2), (4, 3)]


6. (1 punct) Se consideră o matrice de valori care exprimă temperatura măsurată în grade celsius, pe zile, in interval de 24h.

 a) Determinati orele cu temperaturi ridicate (>30)

 b) Determinați media pe zile a temperaturilor, precum și valorile minime și maxime.

 c) Realizați o matrice de "confort termic": 


 * Hot - temp>30
 * Comfortable - temp $\in$ [20,30)
 * Cold - temp <20.

    

In [63]:
#  rows=days, columns=hours
temperatures = np.random.randint(15, 35, (7, 24))

# a) 
hot_hours = [j for i in range(temperatures.shape[0])
                for j in range(temperatures.shape[1])
                     if(temperatures[i][j]>30)]
print(hot_hours)
print(' ')

# b) 
daily_max = np.max(temperatures,axis=1)
print(daily_max)
print(' ')

daily_min = np.min(temperatures,axis=1)
print(daily_min)
print(' ')

daily_avg =np.mean(temperatures,axis=1)
print(daily_avg)
print(' ')



# c) 
comfort_matrix = ["hot" if temperatures[i][j]>30 
                  else "comfortable" if 20<=temperatures[i][j]<=30 
                  else "cold" 
                  for i in range(temperatures.shape[0])
                  for j in range(temperatures.shape[1])]

comfort_matrix = np.array(comfort_matrix).reshape(temperatures.shape)
            
print(comfort_matrix)

[3, 5, 6, 17, 20, 21, 2, 4, 18, 22, 2, 20, 2, 12, 13, 4, 8, 10, 8, 13, 16, 2, 3, 10, 13, 15]
 
[34 34 32 34 34 32 34]
 
[17 15 15 15 15 15 15]
 
[26.70833333 23.54166667 22.95833333 23.91666667 24.875      23.33333333
 24.79166667]
 
[['comfortable' 'comfortable' 'comfortable' 'hot' 'cold' 'hot' 'hot'
  'comfortable' 'comfortable' 'comfortable' 'comfortable' 'comfortable'
  'comfortable' 'comfortable' 'comfortable' 'comfortable' 'comfortable'
  'hot' 'comfortable' 'cold' 'hot' 'hot' 'comfortable' 'comfortable']
 ['comfortable' 'cold' 'hot' 'cold' 'hot' 'comfortable' 'comfortable'
  'comfortable' 'comfortable' 'comfortable' 'comfortable' 'comfortable'
  'cold' 'comfortable' 'comfortable' 'cold' 'cold' 'cold' 'hot' 'cold'
  'comfortable' 'comfortable' 'hot' 'cold']
 ['cold' 'comfortable' 'hot' 'comfortable' 'comfortable' 'comfortable'
  'comfortable' 'comfortable' 'cold' 'comfortable' 'comfortable' 'cold'
  'comfortable' 'comfortable' 'comfortable' 'comfortable' 'cold' 'cold'
  'comforta